### ISSUE TITLE
Replace drf-yasg with drf-spectacular

### ISSUE THREAD

**Issue by annashamray** [maykinmedia/commonground-api-common#29]
**Tasks:**
* [x] Replace drf-yasg custom inspectors with drf-yasg extensions
* [x] Keep the support of all existing schema customization, including error responses, separate content type for error responses, security definition, headers...
* [x] Add tests for schema generation

**What to keep and refactor:** 
* field inspectors to field extensions:
   * [x] geometry field
   * [x] gegevensgroep
   * [x] base64 file (optional, used only in Open Zaak i think )
   * [x] hyperlink identity field
* serializer inspectors to extensions:
   * [x] polymorphic 
* query inspectors to extensions:
   * [x] camelize names
* autoschema customization:
  * [x] add error responses
  * [x] separate content type for error responses
  * [x] customize operation_id (optional, can be done later)
  * [ ] search request serializer (optional) 
  * [x] content-type header
  * [x] geo headers
  * [x] version header
  * [x] cache (eTag) headers and HEAD action description
  * [ ] audittrail headers
  * [x] location header

**Comment by stevenbal** [comment]
@bart-maykin it might be good to use the overrides made in this PR and move them to `commonground-api-common` as well https://github.com/open-zaak/open-notificaties/pull/145#discussion_r1592460424 (if they aren't in Chris' PR already)

**Comment by joeribekker** [comment]
Refinement: Anna and Bart will discuss this to resolve issues.
